### PR TITLE
Nodejs week2

### PR DESCRIPTION
**Pull request by noushinjalali**
This pull request  involves creating a basic search engine using Express.js.

### CODE REVIEW

**Comment by magdazelena** [comment]
hey @noushinjalali I see there is some trouble in your PRs. Normally the code you submit for the PR is the only changes that has been made since the last time. I see in this PR so many stuff from the past weeks... I wonder what can be the problem, but maybe you should review the git maintance with your teammates or me on Sunday? It's very difficult to review complex PRs, but also it's against the practices and we should figure out where the problem is during the course so you are best prepared for the job after :)

**Comment by noushinjalali** [comment]
> hey @noushinjalali I see there is some trouble in your PRs. Normally the code you submit for the PR is the only changes that has been made since the last time. I see in this PR so many stuff from the past weeks... I wonder what can be the problem, but maybe you should review the git maintance with your teammates or me on Sunday? It's very difficult to review complex PRs, but also it's against the practices and we should figure out where the problem is during the course so you are best prepared for the job after :)



> hey @noushinjalali I see there is some trouble in your PRs. Normally the code you submit for the PR is the only changes that has been made since the last time. I see in this PR so many stuff from the past weeks... I wonder what can be the problem, but maybe you should review the git maintance with your teammates or me on Sunday? It's very difficult to review complex PRs, but also it's against the practices and we should figure out where the problem is during the course so you are best prepared for the job after :)


Hi Magdalena,
Unfortunately, I couldn't attend the class in person on Sunday due to food poisoning. Yes, you're right, I had an issue connecting to MySQL, and in the process of trying to fix it, I made a lot of mistakes. Eventually, out of sheer exhaustion, I mistakenly pushed my homework to last week's branch! With my spouse's help, I resolved the MySQL issue, deleted my homework, and started rewriting them from the first week of Node.js. I will fix all these problems soon. Thank you for your guidance🤍

**Review by magdazelena — APPROVED** [review]
nice work! I absolutely understand the circustances :) please make sure to take your time in the future and submit clean PRs - it's better for you in the long run not to push yourself and make the code clear for your future self :)

**Comment by noushinjalali** [comment]
> nice work! I absolutely understand the circustances :) please make sure to take your time in the future and submit clean PRs - it's better for you in the long run not to push yourself and make the code clear for your future self :)

> you're right, i wasted my time, because i was tired :( i just finished and have push the 3rd week PR

**Pull request merged**
